### Importando e verificando se o tensorflow foi instalado

In [1]:
import tensorflow as tf

C:\Users\Natielle\anaconda3\envs\tensorflow2_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Natielle\anaconda3\envs\tensorflow2_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Natielle\anaconda3\envs\tensorflow2_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Natielle\anaconda3\env

In [2]:
tf.__version__

'1.13.2'

# Declarando tipos de dados

### Constantes 

In [3]:
a = tf.constant(4)
b = tf.constant(5, name = 'variavelB')

In [4]:
print(a)
type(a)

Tensor("Const:0", shape=(), dtype=int32)


tensorflow.python.framework.ops.Tensor

In [5]:
print(b)
type(b)

Tensor("variavelB:0", shape=(), dtype=int32)


tensorflow.python.framework.ops.Tensor

### Vetores


In [6]:
vetA = tf.constant([1,2,3])
vetB = tf.constant([4,5,6], name = 'vetorB')

In [7]:
print(vetA)
type(vetA)

print(vetB)
type(vetB)

Tensor("Const_1:0", shape=(3,), dtype=int32)
Tensor("vetorB:0", shape=(3,), dtype=int32)


tensorflow.python.framework.ops.Tensor

### Matrizes


In [8]:
matA = tf.constant([[1,2,3],[4,5,6]])
matB = tf.constant([[7,8,9],[3,2,1]], name = 'matrizB')

In [9]:
print(matA)
type(matA)

print(matB)
type(matB)

Tensor("Const_2:0", shape=(2, 3), dtype=int32)
Tensor("matrizB:0", shape=(2, 3), dtype=int32)


tensorflow.python.framework.ops.Tensor

# Realizando operações básicas com o tensorflow


## Soma

### Soma de constantes

In [10]:
soma = a + b # somando constantes

In [11]:
type(soma)
print(soma)

Tensor("add:0", shape=(), dtype=int32)


In [12]:
# Executando de fato a soma
with tf.Session() as sess:
    print(sess.run(soma))

9


Ao efetuar a soma, o resultado será 9 pois a = 4 e b = 5.

### Soma de constantes a vetores e matrizes 

In [13]:
soma_constvet = vetA + a

In [14]:
soma_constmat = matA + a

In [15]:
print("a: ", a)
print("vetA: ", vetA)
print("matA: ", matA)

with tf.Session() as sess:
    print("\nConst A: \n")
    print(sess.run(a))
    print("\nVetA: \n")
    print(sess.run(vetA))
    print("\nMatA: \n")
    print(sess.run(matA))
    print("\nSoma vetor e constante: \n")
    print(sess.run(soma_constvet))
    print("\nSoma matriz e constante: \n")
    print(sess.run(soma_constmat))

a:  Tensor("Const:0", shape=(), dtype=int32)
vetA:  Tensor("Const_1:0", shape=(3,), dtype=int32)
matA:  Tensor("Const_2:0", shape=(2, 3), dtype=int32)

Const A: 

4

VetA: 

[1 2 3]

MatA: 

[[1 2 3]
 [4 5 6]]

Soma vetor e constante: 

[5 6 7]

Soma matriz e constante: 

[[ 5  6  7]
 [ 8  9 10]]


### Somas de vetores


In [16]:
soma_vet = vetA + vetB

In [17]:
type(soma_vet)
print(soma_vet)

Tensor("add_3:0", shape=(3,), dtype=int32)


In [18]:
# Executando de fato a soma
with tf.Session() as sess:
    print(sess.run(soma_vet))

[5 7 9]


A soma dos vetores é [5 7 9] porque o vetA = [1 2 3] e o vetB = [4 5 6]. 

### Somas de matrizes


In [19]:
soma_mat = matA + matB

In [20]:
type(soma_mat)
print(soma_mat)

Tensor("add_4:0", shape=(2, 3), dtype=int32)


In [21]:
# Executando de fato a soma
with tf.Session() as sess:
    print(sess.run(soma_mat))

[[ 8 10 12]
 [ 7  7  7]]


A soma das matrizes é [[ 8 10 12 ], [ 7  7  7 ]] porque a 

matA = 

1 | 2 | 3
--- | --- | ---
5 | 6 | 7

e a

matB = 

7 | 8 | 9
--- | --- | ---
3 | 2 | 1
.

Caso as matrizes possuam dimensões diferentes, vamos ver o que acontece.


In [22]:
matC = tf.constant([[1,2],[4,5]])
matD = tf.constant([[7,8,9],[3,2,1], [3,2,1]])
matE = tf.constant([[1,2],[4,5],[7,8]])
matF = tf.constant([[7,8,9],[3,2,1]])

print(matA)
print(matB)
print(matC)
print(matD)
print(matE)
print(matF)


Tensor("Const_2:0", shape=(2, 3), dtype=int32)
Tensor("matrizB:0", shape=(2, 3), dtype=int32)
Tensor("Const_3:0", shape=(2, 2), dtype=int32)
Tensor("Const_4:0", shape=(3, 3), dtype=int32)
Tensor("Const_5:0", shape=(3, 2), dtype=int32)
Tensor("Const_6:0", shape=(2, 3), dtype=int32)


In [23]:
somaAF = matA + matF # o tamanho das matrizes são iguais
# somaEF = matE + matF # não é possível realizar a soma de duas matrizes de tamanhos diferentes (gera erro)
# somaCD = matC + matD # não é possível realizar a soma de duas matrizes de tamanhos diferentes (gera erro)

### Soma de matrizes com vetores

In [24]:
soma_vetmat = vetA + matA 

print("vetA: ", vetA)
print("matA: ", matA)

with tf.Session() as sess:
    print("\nVetA: \n")
    print(sess.run(vetA))
    print("\nMatA: \n")
    print(sess.run(matA))
    print("\nSoma: \n")
    print(sess.run(soma_vetmat))

vetA:  Tensor("Const_1:0", shape=(3,), dtype=int32)
matA:  Tensor("Const_2:0", shape=(2, 3), dtype=int32)

VetA: 

[1 2 3]

MatA: 

[[1 2 3]
 [4 5 6]]

Soma: 

[[2 4 6]
 [5 7 9]]


Como o vetor tem tamanho 3 e a matriz tem tamanho (2 - linhas, 3 - colunas). Então, na soma, o vetor é soma linha a linha.


In [25]:
vetC = tf.constant([2,3]) 
print(vetC) 

Tensor("Const_7:0", shape=(2,), dtype=int32)


Podemos observar aqui que a dimensão de vetC é (2,), ou seja, um vetor linha.


In [26]:
vetD = tf.constant([[5],[3]]) 
print(vetD) 

vetE = tf.constant([2,3,5,6]) 
print(vetE) 

Tensor("Const_8:0", shape=(2, 1), dtype=int32)
Tensor("Const_9:0", shape=(4,), dtype=int32)


Podemos observar aqui que a dimensão de vetD é (2,1), ou seja, um vetor coluna. Mas no fundo, a estrutura é de uma matriz com 2 linhas e 1 coluna.

In [27]:
# soma_vetmat2 = matA + vetC # Não é permitido pois as dimensões são diferentes (gera erro)

In [28]:
soma_vetDmatA = vetD + matA

print("vetD: ", vetD)
print("matA: ", matA)

with tf.Session() as sess:
    print("\nVetD: \n")
    print(sess.run(vetD))
    print("\nMatA: \n")
    print(sess.run(matA))
    print("\nSoma: \n")
    print(sess.run(soma_vetDmatA))

vetD:  Tensor("Const_8:0", shape=(2, 1), dtype=int32)
matA:  Tensor("Const_2:0", shape=(2, 3), dtype=int32)

VetD: 

[[5]
 [3]]

MatA: 

[[1 2 3]
 [4 5 6]]

Soma: 

[[6 7 8]
 [7 8 9]]


Como o vetor tem tamanho 2 e a matriz tem tamanho (2 - linhas, 3 - colunas). Então, na soma, o vetor é soma coluna a coluna.

## Multiplicação
### Multiplicação de constantes


In [29]:
multiplicacao1 = a * b
multiplicacao2 = tf.multiply(a, b)

with tf.Session() as sess:
    print("\na: ", sess.run(a))
    print("\nb: ", sess.run(b))
    print("\nMultiplicação 1: ", sess.run(multiplicacao1))
    print("\nMultiplicação 2: ", sess.run(multiplicacao2))


a:  4

b:  5

Multiplicação 1:  20

Multiplicação 2:  20


### Multiplicação de vetores


In [30]:
multiplicacao_vet1 = vetA * vetB
multiplicacao_vet2 = tf.multiply(vetA, vetB)

with tf.Session() as sess:
    print("------- MULTIPLICANDO VETORES DE MESMO TAMANHO ------")
    print("\nVetA: ", sess.run(vetA))
    print("\nVetB: ", sess.run(vetB))
    print("\nMultiplicação 1: ", sess.run(multiplicacao_vet1))
    print("\nMultiplicação 2: ", sess.run(multiplicacao_vet2))

------- MULTIPLICANDO VETORES DE MESMO TAMANHO ------

VetA:  [1 2 3]

VetB:  [4 5 6]

Multiplicação 1:  [ 4 10 18]

Multiplicação 2:  [ 4 10 18]


In [31]:
# multiplicacao_vet3 = vetA * vetC # Não é possível porque são vetores linhas que não possuem o mesmo tamanho
# Não é possível porque são vetores linhas que não possuem o mesmo tamanho e não funciona também quando os tamanhos são múltiplos
# multiplicacao_vet6 = tf.multiply(vetC, vetE)

multiplicacao_vet4 = tf.multiply(vetC, vetD)
multiplicacao_vet5 = tf.multiply(vetD, vetC)


with tf.Session() as sess:
    print("------- MULTIPLICANDO VETORES DE TAMANHOS DIFERENTES ------")
    print("\nVetA: ", sess.run(vetA))
    print("\nVetC: ", sess.run(vetC))
    print("\nVetD: ", sess.run(vetD))
    print("\nVetE: ", sess.run(vetE))
    print("\nMultiplicação de C e D: ", sess.run(multiplicacao_vet4))
    print("\nMultiplicação de D e C: ", sess.run(multiplicacao_vet5))

------- MULTIPLICANDO VETORES DE TAMANHOS DIFERENTES ------

VetA:  [1 2 3]

VetC:  [2 3]

VetD:  [[5]
 [3]]

VetE:  [2 3 5 6]

Multiplicação de C e D:  [[10 15]
 [ 6  9]]

Multiplicação de D e C:  [[10 15]
 [ 6  9]]


Nota-se também que na multiplicação de vetores não importa ordem da multiplicação.

### Multiplicação de matrizes

In [32]:
# Relembrando cada matriz criada até agora
with tf.Session() as sess:
    print("\nMatA: \n", sess.run(matA))
    print("\nMatB: \n", sess.run(matB))
    print("\nMatC: \n", sess.run(matC))
    print("\nMatD: \n", sess.run(matD))
    print("\nMatE: \n", sess.run(matE))
    print("\nMatF: \n", sess.run(matF))


MatA: 
 [[1 2 3]
 [4 5 6]]

MatB: 
 [[7 8 9]
 [3 2 1]]

MatC: 
 [[1 2]
 [4 5]]

MatD: 
 [[7 8 9]
 [3 2 1]
 [3 2 1]]

MatE: 
 [[1 2]
 [4 5]
 [7 8]]

MatF: 
 [[7 8 9]
 [3 2 1]]


In [33]:
multiplicacao_matAB1 = matA * matB
multiplicacao_matAB2 = tf.multiply(matA, matB)
multiplicacao_matAB3 = tf.multiply(matB, matA)
# multiplicacao_matAB4 = tf.matmul(matA, matB) # Gera erro por não terem o mesmo tamanho
# multiplicacao_matAB5 = tf.matmul(matB, matA) # Gera erro por não terem o mesmo tamanho



In [34]:
with tf.Session() as sess:
    print("\nMultiplicação 1: \n", sess.run(multiplicacao_matAB1))
    print("\nMultiplicação 2: \n", sess.run(multiplicacao_matAB2))
    print("\nMultiplicação 3: \n", sess.run(multiplicacao_matAB3))


Multiplicação 1: 
 [[ 7 16 27]
 [12 10  6]]

Multiplicação 2: 
 [[ 7 16 27]
 [12 10  6]]

Multiplicação 3: 
 [[ 7 16 27]
 [12 10  6]]


Nota-se que nessas multiplicações, há uma multiplicação de elemento a elemento. Não se trata da multiplicação de matrizes da algebra linear, onde a ordem da multiplicação afeta o resultado e os tamanhos precisam ser compatíveis.

In [35]:
multiplicacao_matEF1 = tf.matmul(matE, matF) # matrizes de tamanhos (3,2) e (2,3). Resulta em uma (3,3).
multiplicacao_matEF2 = tf.matmul(matF, matE) # matrizes de tamanhos (2,3) e (3,2). Resulta em uma (2,2).

In [36]:
with tf.Session() as sess:
    print("\nMultiplicação 1: \n", sess.run(multiplicacao_matEF1))
    print("\nMultiplicação 2: \n", sess.run(multiplicacao_matEF2))


Multiplicação 1: 
 [[13 12 11]
 [43 42 41]
 [73 72 71]]

Multiplicação 2: 
 [[102 126]
 [ 18  24]]


Neste caso, estamos multiplicando matrizes pela algebra linear e podemos notar que, de fato, os resultados são alterados pela ordem da multiplicação.

## Produto escalar

O produto escalar nada mais é do que a multiplicação de cada elemento dos vetores e a soma de todos ao final. Em redes neurais o produto escalar é muito útil porque teremos entradas e pesos, então vamos fazer o produto escalar da entrada e os pesos para passar para a função de ativação.


In [37]:
# Simulando matrizes de entrada e dos pesos
matEntrada = tf.constant([[-1.,7.,5.]], name = 'entradas')
matPesos = tf.constant([[0.8,0.1,0.1]], name = 'pesos')

print("Entrada: ", matEntrada)
print("Pesos: ", matPesos)

Entrada:  Tensor("entradas:0", shape=(1, 3), dtype=float32)
Pesos:  Tensor("pesos:0", shape=(1, 3), dtype=float32)


Podemos ver que são vetores coluna e que eles possuem o mesmo tipo de dado. Temos que deixar com o mesmo tipo para que a gente consiga multiplicar esses vetores coluna que possuem a estrutura de uma matriz. Porém, conceitualmente são vetores coluna.

In [38]:
multiplicacao_entr_peso = tf.multiply(matEntrada, matPesos)
produto_escalar_entr_peso = tf.reduce_sum(multiplicacao_entr_peso)

In [39]:
with tf.Session() as sess:
    print("Entrada: \n", sess.run(matEntrada))
    print("Pesos \n", sess.run(matPesos))
    print("Multiplicação: \n", sess.run(multiplicacao_entr_peso))
    print("Produto escalar: \n", sess.run(produto_escalar_entr_peso))

Entrada: 
 [[-1.  7.  5.]]
Pesos 
 [[0.8 0.1 0.1]]
Multiplicação: 
 [[-0.8  0.7  0.5]]
Produto escalar: 
 0.39999998


## Placeholders


In [40]:
primeiro_placeholder = tf.placeholder(dtype='float', shape=None)
# dtype indica o tipo de dado que o placeholder irá receber
# shape indica a dimensão a ser recebidaa, nesse caso, None indica que não se sabe então poderia receber qualquer uma

In [41]:
operacao_soma = primeiro_placeholder + 2

In [42]:
with tf.Session() as sess:
    resultado_vetor = sess.run(operacao_soma, feed_dict = {primeiro_placeholder: [1,2,3]})
    print("Quando o placeholder é um vetor: ", resultado_vetor)
    
    resultado_matriz = sess.run(operacao_soma, feed_dict = {primeiro_placeholder: [[1,2,3],[2,3,4]]})
    print("Quando o placeholder é uma matriz: \n", resultado_matriz)

Quando o placeholder é um vetor:  [3. 4. 5.]
Quando o placeholder é uma matriz: 
 [[3. 4. 5.]
 [4. 5. 6.]]


Notar que por mais que colocamos valores inteiros, quando o placeholder recebe os valores de fato (com feed_dict) ele converte para float.

Outro ponto a se notar é que podemos atribuir ao placeholder uma matriz ou um vetor porque não definimos as dimensões ao criá-lo (com a propriedade shape=None).

In [43]:
# Criando mais um placeholders de exemplo
segundo_placeholder = tf.placeholder(dtype='float', shape=[None,5])
# dtype indica o tipo de dado que o placeholder irá receber
# shape indica a dimensão recebida, nesse caso, temos que passar uma estrutura com X linhas e 5 colunas necessariamente.

In [44]:
operacao_multiplicacao = segundo_placeholder * 3

In [45]:
with tf.Session() as sess:    
    resultado1 = sess.run(operacao_multiplicacao, feed_dict = {segundo_placeholder: [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]})
    print("Quando o placeholder é uma matriz com 3 linhas e 5 colunas: \n", resultado1)
    
    resultado2 = sess.run(operacao_multiplicacao, feed_dict = {segundo_placeholder: [[5,10,15,20,25]]})
    print("\nQuando o placeholder é uma matriz com 1 linhas e 5 colunas: \n", resultado2)

Quando o placeholder é uma matriz com 3 linhas e 5 colunas: 
 [[ 3.  6.  9. 12. 15.]
 [ 3.  6.  9. 12. 15.]
 [ 3.  6.  9. 12. 15.]]

Quando o placeholder é uma matriz com 1 linhas e 5 colunas: 
 [[15. 30. 45. 60. 75.]]


## Grafos com TensorBoard


In [46]:
tf.reset_default_graph() # Limpa o que já estiver na memória relacionado aos grafos

In [47]:
# Criando operações para mostrarmos seu grafo depois
operacao_adicao = tf.add(3, 4, name='add')
operacao_multi = tf.multiply(operacao_adicao, 2, name='multiplicacao')
operacao_divisao = tf.math.divide(operacao_multi, operacao_adicao, name='divisao')

In [48]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('grafos_gerados', sess.graph)
    print(sess.run(operacao_divisao)) # Como a operacao_divisao depende de outras operações, elas são realizadas implicitamente
    writer.close()

2.0


**Como mostrar o grafo?**

Após executado o código acima, haverá uma pasta chamada 'grafos_gerados' na mesma pasta do script com um arquivo. Para abrirmos esse arquivo teremos que rodar o tensor board.

Abrimos o prompt anaconda3, mudamos o environment para o atual com 'conda activate tensorflow2_py37'.

Executamos o comando: 'tensorboard --logdir=caminho_da_pasta_grafos_gerados'.

No meu caso, foi: 'tensorboard --logdir=\Users\Natielle\grafos_gerados' e após executado, irá aparecer um link http. Então você copia e cola no navegador para visualizar o grafo gerado pelas operações que fizemos acima.

*OBS:* Nome meu caso apareceu o link http://DESKTOP-EOST8AC:6006 e eu mudei para http://localhost:6006/para funcionar e deu certo.

![Grafo gerado](grafos_gerados/grafo_gerado.png)

**Podemos criar escopos também quando temos operações mais complexas e maiores. Assim organizamos melhor as ideias. Vamos ver como faz abaixo.**

In [49]:
tf.reset_default_graph() # Limpa o que já estiver na memória relacionado aos grafos para não sobrescrever outros grafos

In [50]:
# Criando operações com escopo para mostrarmos seu grafo depois
with tf.name_scope('Operacoes_para_exemplo'): # não pode ter espaços no nome
    with tf.name_scope('Escopo_A'):
        operacao_A = tf.add(3, 4, name='A') 
    with tf.name_scope('Escopo_B'):  # não pode ter espaços no nome
        operacao_M = tf.multiply(operacao_A, 2, name='M')
        operacao_D = tf.math.divide(operacao_M, operacao_A, name='D')

In [51]:
# Gerando o arquivo para exibir o grafo
with tf.Session() as sess:
    writer = tf.summary.FileWriter('grafos_gerados', sess.graph)
    print(sess.run(operacao_D)) # Como a operacao_divisao depende de outras operações, elas são realizadas implicitamente
    writer.close()

2.0


Para mostrar o grafo, fazer os mesmos passos de "Como mostrar o grafo?" caso o tensorboard não tiver executando.

Caso o tensorboard já esteja executando, basta executar o código acima e atualizar a página do navegador.

O resultado esperado do grafo acima é: ![Grafo com escopo](grafos_gerados/grafo_gerado_com_escopo.png)